### ISSUE TITLE
What are pose-matcher-configs?

### ISSUE THREAD

**Issue by cstenkamp** [frankier/skelshop#28]
While track-confs are understandable as one of `click.Choice(TRACK_CONFS.keys())` I don't understand what a pose-matcher-config is even? What is supposed to be stated there as `Text`?

**Comment by frankier** [comment]
This is for the skeleton based reidentification. The models from lighttrack are used for this https://github.com/Guanghan/lighttrack

This is only needed if you use the lighttrackish tracker, but this is currently the best I think.

Everything is handled by default for the current best settings by the Snakemake configuration: https://github.com/frankier/skelshop/blob/master/workflow/Snakefile https://github.com/frankier/skelshop/blob/master/workflow/rules/skels.smk

Documenting usage via Snakemake is on the TODO https://github.com/frankier/skelshop/issues/21

**Comment by frankier** [comment]
In short, if you follow the installation instructions or use the Dockerfile, you should already have it at `work//gcn_config.yaml`

**Comment by frankier** [comment]
Here's where the magic happens https://github.com/frankier/skelshop/blob/dfff53eeaa7ec47ff064b6a793a29f0e8d85e79e/skelshop/pipeline.py#L81

But this whole part is one of the ugliest bits of this whole thing because we have to pull in a bunch of horrible stuff to get the pretrained lighttrack model to work. It would be nice to clean this up at some point, but perhaps it's less important if we switch to a pose estimator which already does tracking.

**Comment by frankier** [comment]
Sorry that should have been opt_lighttrack is the best

**Comment by frankier** [comment]
Closing as answered. Feel free to reopen.
